apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: backend-tests-nodejs-jovndnjk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend-tests-nodejs-jovndnjk 
  name: backend-tests-nodejs-jovndnjk
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: backend-tests-nodejs-jovndnjk
    weight: 100 
